In [1]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [23]:
array = np.random.randint(1,10, size=(3,3))
print ("Initial Array")
print (array)
print("\n")
array[[0, 2]] = array[[2, 0]]
print ("1st and 3rd row swapped")
print (array)

Initial Array
[[4 1 7]
 [3 3 8]
 [7 7 6]]


1st and 3rd row swapped
[[7 7 6]
 [3 3 8]
 [4 1 7]]


**75. How to compute averages using a sliding window over an array?**

In [34]:
array = np.random.randint(1,10, size=(3,3))
print (array)
a = np.cumsum(array)
print("\n")
print (a)
print ("Average:", round(np.average(a),2))


[[6 1 8]
 [6 9 6]
 [4 8 1]]


[ 6  7 15 21 30 36 40 48 49]
Average: 28.0
